### ISSUE TITLE
bug: `pydantic` import error

### ISSUE THREAD

**Issue by ReubenFrankel** [MeltanoLabs/target-chromadb#8]
```
reuben@reuben-Inspiron-14-5425:~/tmp/FoundationSearch-qcofrab$ meltano invoke target-chromadb
2023-07-10T09:27:04.018387Z [info     ] Environment 'dev' is active
Traceback (most recent call last):
  File "/home/reuben/tmp/FoundationSearch-qcofrab/.meltano/loaders/target-chromadb/venv/bin/target-chromadb", line 5, in <module>
    from target_chromadb.target import TargetChroma
  File "/home/reuben/tmp/FoundationSearch-qcofrab/.meltano/loaders/target-chromadb/venv/lib/python3.10/site-packages/target_chromadb/target.py", line 8, in <module>
    from target_chromadb.sinks import (
  File "/home/reuben/tmp/FoundationSearch-qcofrab/.meltano/loaders/target-chromadb/venv/lib/python3.10/site-packages/target_chromadb/sinks.py", line 7, in <module>
    import chromadb
  File "/home/reuben/tmp/FoundationSearch-qcofrab/.meltano/loaders/target-chromadb/venv/lib/python3.10/site-packages/chromadb/__init__.py", line 1, in <module>
    import chromadb.config
  File "/home/reuben/tmp/FoundationSearch-qcofrab/.meltano/loaders/target-chromadb/venv/lib/python3.10/site-packages/chromadb/config.py", line 1, in <module>
    from pydantic import BaseSettings
  File "/home/reuben/tmp/FoundationSearch-qcofrab/.meltano/loaders/target-chromadb/venv/lib/python3.10/site-packages/pydantic/__init__.py", line 206, in __getattr__
    return _getattr_migration(attr_name)
  File "/home/reuben/tmp/FoundationSearch-qcofrab/.meltano/loaders/target-chromadb/venv/lib/python3.10/site-packages/pydantic/_migration.py", line 279, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0.2/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.0.2/u/import-error
```

Can work around by constraining with `pydantic<2`:

```yml
  - name: target-chromadb
    variant: meltanolabs
    pip_url: git+https://github.com/meltanolabs/target-chromadb.git 'pydantic<2'
```

**Comment by ReubenFrankel** [comment]
Looks related to https://github.com/chroma-core/chroma/issues/774
